### ISSUE TITLE
Tanner-web not starting

### ISSUE THREAD

**Issue by viskey98** [mushorg/snare#114]
I ran tanner-web in master branch and i get this error:
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 401, in __init__
    raise ValueError('Not a directory')
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tannerweb", line 4, in <module>
    __import__('pkg_resources').run_script('Tanner==0.5.0', 'tannerweb')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/EGG-INFO/scripts/tannerweb", line 20, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/EGG-INFO/scripts/tannerweb", line 16, in main
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/tanner/web/server.py", line 117, in start
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/tanner/web/server.py", line 110, in create_app
  File "/usr/local/lib/python3.6/dist-packages/Tanner-0.5.0-py3.6.egg/tanner/web/server.py", line 103, in setup_routes
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 850, in add_static
    follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 404, in __init__
    "No directory exists at '{}'".format(directory)) from error
ValueError: No directory exists at '/tanner/web/static'
```

**Comment by afeena** [comment]
You need to run it in the tanner directory. And please, move the issue to tanner

**Comment by viskey98** [comment]
sorry issue was created in the wrong project
