### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype

### ISSUE THREAD

**Issue by chumperz** [mushorg/snare#148]
I have an issue with installing this using a raspberry pi. I follow the instructions and everything however after running the command : "sudo python3 snare.py --port 8080 --page-dir example.com" 
below is the response(in CLI) when I visit the url localhost:8080 : 

```
privileges dropped, running as "nobody:nogroup"
serving on ('::1', 8080) with uuid ed786207-1b21-4f9c-a1bd-10403b8d8a53
you are running the latest version
Request path: /
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
Expecting value: line 1 column 1 (char 0) {'headers': {'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.89 Safari/537.36', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Host': 'localhost:8080', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'}, 'method': 'GET', 'status': 200, 'uuid': 'ed786207-1b21-4f9c-a1bd-10403b8d8a53', 'path': '/', 'peer': {'ip': '::1', 'port': 59184}}
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:225> exception=TypeError('TypeError("\'NoneType\' object is not subscriptable",) is not JSON serializable',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 275, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 192, in handle_request
    request.path, event_result['response']['message']['detection'])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 325, in start
    yield from self.handle_error(500, message, None, exc)
  File "snare.py", line 289, in handle_error
    await self.submit_data(data)
  File "snare.py", line 134, in submit_data
    raise e
  File "snare.py", line 125, in submit_data
    'http://{0}:8090/event'.format(self.run_args.tanner), data=json.dumps(data)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: TypeError("'NoneType' object is not subscriptable",) is not JSON serializable

```

**Comment by afeena** [comment]
Hi, have you used default tanner or you run your own?

**Comment by chumperz** [comment]
Hi afeena, No, this is my first time to install Snare, isn't it Tanner is optional install?

**Comment by viskey98** [comment]
@afeena It seems, default tanner is facing some problem handling the request. We should check error logs in (default) tanner's side for more info.
