### ISSUE TITLE
ValueError Upon Cloning Website

### ISSUE THREAD

**Issue by olivia-oj** [mushorg/snare#150]
I attempted to clone a website with the following command (snare is the name of this project's virtualenv) `sudo snare/bin/python3 clone.py --target https://gcbaz.com/`

I received this traceback in response:

```
Traceback (most recent call last):
  File "clone.py", line 221, in <module>
    main()
  File "clone.py", line 215, in main
    loop.run_until_complete(cloner.run())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "clone.py", line 190, in run
    await self.get_body(session)
  File "clone.py", line 148, in get_body
    response = await session.get(current_url)
  File "/home/oliviao/snare/snare/local/lib/python3.5/site-packages/aiohttp/client.py", line 590, in __await__
    resp = yield from self._coro
  File "/home/oliviao/snare/snare/local/lib/python3.5/site-packages/aiohttp/client.py", line 215, in _request
    proxy=proxy, proxy_auth=proxy_auth, timer=timer)
  File "/home/oliviao/snare/snare/local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 95, in __init__
    self.update_host(url)
  File "/home/oliviao/snare/snare/local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 120, in update_host
    "Could not parse hostname from URL '{}'".format(url))
ValueError: Could not parse hostname from URL 'about:blank'
```
Would appreciate a fix or suggestions on how to avoid this error.

**Comment by afeena** [comment]
Hi @olivia-oj 
I made a hot fix for this problem, I hope this helps :)
I tested it with website from your command. Please, let me know if you still have a problems

**Comment by olivia-oj** [comment]
I think the commit is referencing the wrong issue number but other than that all good. The error is no longer raised. Thanks so much!
