### ISSUE TITLE
KeyError 'status_404'

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/snare#154]
When running latest Snare 0.3 I am getting the following error and Snare exits:

```
/opt/snare # snare --debug true --no-dorks true --auto-update false --host-ip 0.0.0.0 --port 80 --page-dir example.com

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

    
privileges dropped, running as "nobody:nobody"
serving with uuid 9e0d0953-e246-467b-b637-29ca8b1ad776
Debug logs will be stored in /opt/snare/snare.log
Error logs will be stored in /opt/snare/snare.err
Traceback (most recent call last):
  File "/usr/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 204, in <module>
  File "/usr/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 91, in start
KeyError: '/status_404'
```

**Comment by viskey98** [comment]
@t3chn0m4g3 Did you clone the page again after latest snare update?

**Comment by t3chn0m4g3** [comment]
@viskey98 Yes. Rebuild the Docker container, used the latest setup instructions and cloned the page again.

**Comment by viskey98** [comment]
@t3chn0m4g3 can you please show your clone output?

**Comment by t3chn0m4g3** [comment]
cloner says it cannot resolve `example.com`, however the container is able to resolve it just fine:
```
/opt/snare # clone --target example.com

    ______ __      ______ _   ____________
   / ____// /     / __  // | / / ____/ __ \
  / /    / /     / / / //  |/ / __/ / /_/ /
 / /___ / /____ / /_/ // /|  / /___/ _, _/
/_____//______//_____//_/ |_/_____/_/ |_|
    
    
Error logs will be stored in /opt/snare/clone.err

name:  /index.html
name:  /status_404
/opt/snare # cat clone.err 
2018-08-02 17:53:51 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:29:51 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:30:30 ERROR:snare.cloner:get_body: Cannot connect to host https:80 ssl:None [Name does not resolve]
2018-08-02 18:30:39 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:31:05 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:31:52 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:32:36 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
/opt/snare # ping example.com
PING example.com (93.184.216.34): 56 data bytes
64 bytes from 93.184.216.34: seq=0 ttl=54 time=93.688 ms
64 bytes from 93.184.216.34: seq=1 ttl=54 time=93.107 ms
^C
--- example.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 93.107/93.397/93.688 ms
```

Same result with protocol...:
```
/opt/snare # clone --target http://example.com

    ______ __      ______ _   ____________
   / ____// /     / __  // | / / ____/ __ \
  / /    / /     / / / //  |/ / __/ / /_/ /
 / /___ / /____ / /_/ // /|  / /___/ _, _/
/_____//______//_____//_/ |_/_____/_/ |_|
    
    
Error logs will be stored in /opt/snare/clone.err

name:  /index.html
name:  //example.com/status_404
/opt/snare # cat clone.err 
2018-08-02 17:53:51 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:29:51 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:30:30 ERROR:snare.cloner:get_body: Cannot connect to host https:80 ssl:None [Name does not resolve]
2018-08-02 18:30:39 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:31:05 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:31:52 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:32:36 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]
2018-08-02 18:35:55 ERROR:snare.cloner:get_body: Cannot connect to host http:80 ssl:None [Name does not resolve]

```

**Comment by viskey98** [comment]
@t3chn0m4g3 I don't understand why the url is not getting resolved. But I know the error which you are facing happens when we use a page which was cloned the outdated cloner (snare 0.2).
Please try to
1. delete all the pages (keeping in mind they are outdated) in `/opt/snare/pages`
2. clone a fresh page  For example : ` clone --target www.github.com --max-depth 1`
3. Try to run snare.
Remember as long as you use old pages which are found in directory `/opt/snare/pages`, this error will keep occuring.

**Comment by t3chn0m4g3** [comment]
@viskey98 Thanks for your swift response.
1. Always building docker images from scratch, so no outdated pages are possible.
2. Did a fresh clone, same error.
3. Same error.

After removing `WORKDIR /opt/snare`from `Dockerfile` and thus running clone outside `/opt/snare` everything works fine.

Strange though, since everything is built from `master` when building the image.

Thanks for your help :bowtie:

**Comment by viskey98** [comment]
Yes that's strange, glad that it works fine now :slightly_smiling_face:

**Comment by t3chn0m4g3** [comment]
Something is still off... It does not work if the protocol is prefixed (http://example.com), without (example.com) it works fine.

**Comment by viskey98** [comment]
@t3chn0m4g3 thanks for finding this issue, It seems to be a small bug. I have created a pr fixing this issue.

**Comment by t3chn0m4g3** [comment]
Confirmed. Thanks @viskey98 @afeena
