### ISSUE TITLE
Binding to port <1024 does not seem to work

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/snare#156]
Even when running as `root` I cannot seem to get snare binding to `--port=80`:
```
/ # /usr/bin/snare --page-dir example.com --port 80 --host-ip 0.0.0.0 --debug true --no-dorks true

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

    
privileges dropped, running as "nobody:nobody"
serving with uuid 83d5afd7-dd12-485d-8069-d1c0da07181a
Debug logs will be stored in /opt/snare/snare.log
Error logs will be stored in /opt/snare/snare.err
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1044, in create_server
    sock.bind(sa)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 204, in <module>
  File "/usr/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 93, in start
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 114, in run_app
    loop.run_until_complete(site.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/site-packages/aiohttp/web_runner.py", line 89, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1048, in create_server
    % (sa, err.strerror.lower()))
PermissionError: [Errno 13] error while attempting to bind on address ('0.0.0.0', 80): permission denied
```

Setting `setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python3.6` usually works fine, even when privileges are dropped. However in this case no luck. Only setting port to >=1024 seems to work fine.

**Comment by xandfury** [comment]
Yeah. This has changed recently. Devs should take note ;-)
https://github.com/mushorg/snare/blob/bc913256dbc0ce596328316901684d205645d97d/snare.py#L491-L500
has changed to 
https://github.com/mushorg/snare/blob/30c4dbcbd549746e1cad98bf39b39d4fe8e90b7f/bin/snare#L198-L205

**Comment by t3chn0m4g3** [comment]
@afeena Can you have a look at this. It seems privileges are dropped too early now.

**Comment by t3chn0m4g3** [comment]
@afeena Can you have a look at this 😃

**Comment by afeena** [comment]
@t3chn0m4g3 The problem is that binding now is doing inside the aiohttp library (as @xandfury mentioned, previously binding was done before dropping privileges). I haven't found a quick solution for this problem, but I will try to fix it asap.

**Comment by t3chn0m4g3** [comment]
Awesome!

**Comment by afeena** [comment]
@t3chn0m4g3 I created the pr https://github.com/mushorg/snare/pull/158 for this problem, could you please check if it works for you?

**Comment by t3chn0m4g3** [comment]
@afeena Works perfectly fine! Thank you!

It's merge time 😄

**Comment by afeena** [comment]
@t3chn0m4g3 Done :)

**Comment by t3chn0m4g3** [comment]
Thank you!
