### ISSUE TITLE
AttributeError while running snare

### ISSUE THREAD

**Issue by mzfr** [mushorg/snare#160]
I followed the installation instructions - it compiles, it starts but I am getting an error and then it stops.

```
Traceback (most recent call last):
  File "/usr/local/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/home/mzfr/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mzfr/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/Snare-0.3.0-py3.5.egg/EGG-INFO/scripts/snare", line 205, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/Snare-0.3.0-py3.5.egg/snare/server.py", line 87, in start
AttributeError: 'Application' object has no attribute 'add_routes'
```

**Comment by afeena** [comment]
Hi @mzfr sorry for the late answer. Do you have the same problem now?

**Comment by mzfr** [comment]
Hey, @afeena yes I am still having this problem.
