### ISSUE TITLE
Ubuntu16.04 : cannot assign requested address

### ISSUE THREAD

**Issue by zhang199653** [mushorg/snare#165]
root@e80a08108ced:/opt/snare# snare --port 8080 --page-dir example.com

serving with uuid 6664d0c8-0e42-43c4-9a7a-915097a81969
Debug logs will be stored in /opt/snare/snare.log
Error logs will be stored in /opt/snare/snare.err
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1045, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 205, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 98, in start
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_runner.py", line 89, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1049, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('::1', 8080, 0, 0): cannot assign requested address

**Comment by zhang199653** [comment]
serving with uuid 6664d0c8-0e42-43c4-9a7a-915097a81969
Debug logs will be stored in /opt/snare/snare.log
Error logs will be stored in /opt/snare/snare.err
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1045, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 205, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 98, in start
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_runner.py", line 89, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1049, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('::1', 8080, 0, 0): cannot assign requested address

**Comment by zhang199653** [comment]
I build snare in the docker container and use default command 'snare --port 8080 --page-dir example.com' to start snare,that cause this error.If i add '--host <ip>' parameter can avoid this error.
