### ISSUE TITLE
Cloner fails when trying to scrape google.com

### ISSUE THREAD

**Issue by subhazard** [mushorg/snare#175]
Keep trying to get SNARE to work, and while following the documentation I keep running into issues.

`sudo clone --max-depth 0 --target http://google.com`

 
    
`Error logs will be stored in /opt/snare/clone.err`

`Traceback (most recent call last):
  File "/usr/local/bin/clone", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'clone')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/clone", line 65, in <module>
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/clone", line 50, in main
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/cloner.py", line 165, in get_root_host
AttributeError: 'ClientResponse' object has no attribute '_url_obj'`

**Comment by viskey98** [comment]
@subhazard Thanks for pointing out this bug. This occurred because the latest aiohttp version has a new attribute name for url. I will create a fix for the same :)

**Comment by glaslos** [comment]
I confirmed that the issue has been solved with the current version of SNARE
