### ISSUE TITLE
aiohttp.client_exceptions.ServerDisconnectedError: None

### ISSUE THREAD

**Issue by saucer-man** [mushorg/snare#216]
hi, I try to run this project using docker , but when I  run ``doker-compose up``, error happend
``` 
ubuntu@ubuntu:~/snare# docker-compose up
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
Recreating snare ... done
Attaching to snare
snare    |
snare    |    _____ _   _____    ____  ______
snare    |   / ___// | / /   |  / __ \/ ____/
snare    |   \__ \/  |/ / /| | / /_/ / __/
snare    |  ___/ / /|  / ___ |/ _, _/ /___
snare    | /____/_/ |_/_/  |_/_/ |_/_____/
snare    |
snare    |
snare    | Traceback (most recent call last):
snare    |   File "/usr/local/bin/snare", line 4, in <module>
snare    |     __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
snare    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
snare    |     self.require(requires)[0].run_script(script_name, ns)
snare    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1460, in run_script
snare    |     exec(script_code, namespace, namespace)
snare    |   File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 185, in <module>
snare    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
snare    |     return future.result()
snare    |   File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 113, in check_tanner
snare    |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 391, in _request
snare    |     await resp.start(conn)
snare    |   File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 757, in start
snare    |     message, payload = await self._protocol.read()
snare    |   File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 543, in read
snare    |     await self._waiter
snare    | aiohttp.client_exceptions.ServerDisconnectedError: None
```
I try some other way but this error always exits, help please :)

**Comment by Masood-M** [comment]
Probably because you have python version 2.7 but it requires python 3.6, as the error message says.

**Comment by saucer-man** [comment]
but when I try to install with pip and python3 manual, It still exits...

**Comment by afeena** [comment]
@saucer-man Hi, could you please give me more info about your environment? I can't reproduce the error.

**Comment by saucer-man** [comment]
full process is:
```bash
ubuntu@ubuntu:~/snare$ python3 -V
Python 3.6.8
ubuntu@ubuntu:~/snare$ ls
bin  build  dist  docker-compose.yml  Dockerfile  docs  LICENSE  README.md  readthedocs.yml  requirements.txt  setup.py  snare  Snare.egg-info
ubuntu@ubuntu:~/snare$ sudo pip3 install -r requirements.txt
[sudo] password for ubuntu: 
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: aiohttp==3.4.4 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: aiohttp_jinja2==1.1.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: beautifulsoup4==4.6.3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: cssutils==1.0.2 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: gitpython==2.1.11 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pycodestyle==2.4.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: multidict<5.0,>=4.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: jinja2>=2.7 in /usr/local/lib/python3.6/dist-packages (from aiohttp_jinja2==1.1.0->-r requirements.txt (line 2))
Requirement already satisfied: gitdb2>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from gitpython==2.1.11->-r requirements.txt (line 5))
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2>=2.7->aiohttp_jinja2==1.1.0->-r requirements.txt (line 2))
Requirement already satisfied: smmap2>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from gitdb2>=2.0.0->gitpython==2.1.11->-r requirements.txt (line 5))
ubuntu@ubuntu:~/snare$ sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing Snare.egg-info/PKG-INFO
writing dependency_links to Snare.egg-info/dependency_links.txt
writing top-level names to Snare.egg-info/top_level.txt
reading manifest file 'Snare.egg-info/SOURCES.txt'
writing manifest file 'Snare.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/snare
copying build/lib/snare/tanner_handler.py -> build/bdist.linux-x86_64/egg/snare
copying build/lib/snare/server.py -> build/bdist.linux-x86_64/egg/snare
copying build/lib/snare/cloner.py -> build/bdist.linux-x86_64/egg/snare
copying build/lib/snare/__init__.py -> build/bdist.linux-x86_64/egg/snare
copying build/lib/snare/html_handler.py -> build/bdist.linux-x86_64/egg/snare
creating build/bdist.linux-x86_64/egg/snare/utils
copying build/lib/snare/utils/asyncmock.py -> build/bdist.linux-x86_64/egg/snare/utils
copying build/lib/snare/utils/page_path_generator.py -> build/bdist.linux-x86_64/egg/snare/utils
copying build/lib/snare/utils/logger.py -> build/bdist.linux-x86_64/egg/snare/utils
copying build/lib/snare/utils/snare_helpers.py -> build/bdist.linux-x86_64/egg/snare/utils
copying build/lib/snare/utils/__init__.py -> build/bdist.linux-x86_64/egg/snare/utils
creating build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_html_handler_handle_html_content.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_snare_helpers_converter.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_tanner_handler_parse_tanner_response.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_snare_helpers_add_meta_tag.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_snare_helpers_versions_manager.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_cloner_add_scheme.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_cloner_process_links.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_server_handle_request.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_snare_helpers_parse_timeout.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_snare_helpers_str_to_bool.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_tanner_handler_create_data.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/__init__.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_cloner_make_filename.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_tanner_handler_submit_data.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_cloner_replace_links.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_html_handler_get_dorks.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/tests/test_cloner_get_body.py -> build/bdist.linux-x86_64/egg/snare/tests
copying build/lib/snare/middlewares.py -> build/bdist.linux-x86_64/egg/snare
creating build/bdist.linux-x86_64/egg/bin
copying build/lib/bin/__init__.py -> build/bdist.linux-x86_64/egg/bin
byte-compiling build/bdist.linux-x86_64/egg/snare/tanner_handler.py to tanner_handler.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/server.py to server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/cloner.py to cloner.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/html_handler.py to html_handler.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/utils/asyncmock.py to asyncmock.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/utils/page_path_generator.py to page_path_generator.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/utils/logger.py to logger.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/utils/snare_helpers.py to snare_helpers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/utils/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_html_handler_handle_html_content.py to test_html_handler_handle_html_content.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_snare_helpers_converter.py to test_snare_helpers_converter.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_tanner_handler_parse_tanner_response.py to test_tanner_handler_parse_tanner_response.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_snare_helpers_add_meta_tag.py to test_snare_helpers_add_meta_tag.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_snare_helpers_versions_manager.py to test_snare_helpers_versions_manager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_cloner_add_scheme.py to test_cloner_add_scheme.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_cloner_process_links.py to test_cloner_process_links.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_server_handle_request.py to test_server_handle_request.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_snare_helpers_parse_timeout.py to test_snare_helpers_parse_timeout.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_snare_helpers_str_to_bool.py to test_snare_helpers_str_to_bool.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_tanner_handler_create_data.py to test_tanner_handler_create_data.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_cloner_make_filename.py to test_cloner_make_filename.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_tanner_handler_submit_data.py to test_tanner_handler_submit_data.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_cloner_replace_links.py to test_cloner_replace_links.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_html_handler_get_dorks.py to test_html_handler_get_dorks.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/tests/test_cloner_get_body.py to test_cloner_get_body.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/snare/middlewares.py to middlewares.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/bin/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/snare -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/clone -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/snare to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/clone to 755
copying Snare.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Snare.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Snare.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Snare.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Snare-0.3.0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Snare-0.3.0-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg
Copying Snare-0.3.0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Snare 0.3.0 is already the active version in easy-install.pth
Installing clone script to /usr/local/bin
Installing snare script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg
Processing dependencies for Snare==0.3.0
Finished processing dependencies for Snare==0.3.0
ubuntu@ubuntu:~/snare$ sudo clone --target http://example.com

    ______ __      ______ _   ____________
   / ____// /     / __  // | / / ____/ __ \
  / /    / /     / / / //  |/ / __/ / /_/ /
 / /___ / /____ / /_/ // /|  / /___/ _, _/
/_____//______//_____//_/ |_/_____/_/ |_|

    
Error logs will be stored in /opt/snare/clone.err

name:  /index.html
name:  /status_404
ubuntu@ubuntu:~/snare$ sudo snare --port 8888 --page-dir example.com

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

    
Traceback (most recent call last):
  File "/usr/local/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 185, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 113, in check_tanner
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 543, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
```

Thank you !

**Comment by afeena** [comment]
Can you confirm that your network works correctly? Can you access http://tanner.mushmush.org:8090/ (e.g. from your browser?)

**Comment by saucer-man** [comment]
I checked my network and it can not access that url, the reason may be here, thank you for help
