### ISSUE TITLE
running into issue when following installation guide

### ISSUE THREAD

**Issue by Moooser** [mushorg/snare#222]
when trying to run the "steps to setup" I run into an error at "5. Run SNARE"

odroid@odroid:/opt/snare$ sudo snare --port 8080 --page-dir example.com

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

Traceback (most recent call last):
  File "/usr/local/bin/snare", line 4, in <module>
    __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 185, in <module>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 114, in check_tanner
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

There seems to be an issue with received packets?

Thanks in advance.

**Comment by glaslos** [comment]
Hm, can you try again? This is the call that failed: http://tanner.mushmush.org:8090/version and it seems to be this is returning json.
@rjt-gupta can you add some better error handling for the `check_tanner` function?

**Comment by glaslos** [comment]
I just verified and the header is also `application/json`. Maybe you have a proxy in between or this host is blocked?

**Comment by Moooser** [comment]
Sorry for replying late, was out of office. Thanks for your help. I have a Proxy in between, but I checked the URL from which the content seems to be loaded, "http://tanner.mushmush.org:8090/version" and the proxy doens't block. If I make the request via postman I get a application/json header back.

**Comment by Moooser** [comment]
ok update, I just tried to curl the URL from the machine I am running the script on and indeed the proxy seems to block. Seems to be some weird proxy configuration. Thanks for your help.
