### ISSUE TITLE
Traceback on running snare

### ISSUE THREAD

**Issue by Aniket21mathur** [mushorg/snare#224]
Got internal server error on visiting `localhost:8080`.

`snare.err`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/middlewares.py", line 22, in error_middleware
    response = await handler(request)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 50, in handle_request
    event_result = await self.tanner_handler.submit_data(data)
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 63, in submit_data
    raise e
  File "/usr/local/lib/python3.6/dist-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 56, in submit_data
    event_result = await r.json()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'
```
Possibly because the `content-type` is not passed to the json function or we can instead use `json.loads`.

@afeena @rjt-gupta @rnehra01 please have a look. Thanks!

**Comment by afeena** [comment]
@Aniket21mathur I fixed the problem with default tanner server, you can check it now :)

**Comment by Aniket21mathur** [comment]
@afeena thanks I tried to run snare again with the default tanner server `example.com` but it doesn't run. It stops as shown below in the image. Nothing in the `logs.err`, I am afraid I am not able to figure out why this is happening. 

Please guide. Thanks!
![Screenshot from 2019-12-18 09-53-41](https://user-images.githubusercontent.com/35092582/71055777-e7646880-217c-11ea-9393-87b852344434.png)

**Comment by afeena** [comment]
@Aniket21mathur I suggest you to run `snare` with your own tanner instance. (so you have to run `tanner` first and run `snare` with `--tanner <your tanner server>`)

**Comment by mzfr** [comment]
@afeena This is also happening in docker.

After `docker-compose up` is successful and I try to visit `http://0.0.0.0:80` I get `500 internal server error`.
So I ran `docker exec ca3d4a756928 cat /opt/snare/snare.err`(`ca3d4a756928` is the container ID) and it showed the following:

```
2020-02-24 17:56:23 ERROR:snare.tanner_handler:submit_data: Exception: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 56, in submit_data
    event_result = await r.json()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'
2020-02-24 17:56:23 ERROR:aiohttp.server:log_exception: Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/middlewares.py", line 22, in error_middleware
    response = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/server.py", line 50, in handle_request
    event_result = await self.tanner_handler.submit_data(data)
  File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 63, in submit_data
    raise e
  File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/snare/tanner_handler.py", line 56, in submit_data
    event_result = await r.json()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'
```

**Comment by afeena** [comment]
@mzfr It happened (again) because of the redis problem with default TANNER
please run with your own tanner instance instead
