### ISSUE TITLE
Snare Docker container builds but fails to run

### ISSUE THREAD

**Issue by JesseBowling** [mushorg/snare#245]
Using the existing docker-compose/Dockerfile setup, the snare container will build but fails to run. Specifically, this error is received:

```
8$ docker-compose up
Recreating snare ... done
Attaching to snare
snare    | Traceback (most recent call last):
snare    |   File "/usr/local/bin/snare", line 4, in <module>
snare    |     __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')
snare    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
snare    |     self.require(requires)[0].run_script(script_name, ns)
snare    |   File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1470, in run_script
snare    |     exec(script_code, namespace, namespace)
snare    |   File "/usr/local/lib/python3.6/site-packages/Snare-0.3.0-py3.6.egg/EGG-INFO/scripts/snare", line 29, in <module>
snare    |   File "/usr/local/lib/python3.6/site-packages/git/__init__.py", line 38, in <module>
snare    |     from git.exc import *                       # @NoMove @IgnorePep8
snare    |   File "/usr/local/lib/python3.6/site-packages/git/exc.py", line 9, in <module>
snare    |     from git.compat import UnicodeMixin, safe_decode, string_types
snare    |   File "/usr/local/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
snare    |     from gitdb.utils.compat import (
snare    | ModuleNotFoundError: No module named 'gitdb.utils.compat'
```
If I `pip3 install gitdb` and explore the module, there does not seem to be a `gitdb.utils.compat` available.

```
>>> import gitdb
>>> dir(gitdb.utils)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'encoding']
```

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by mzfr** [comment]
@JesseBowling recently the PR #238 was merged which should have fixed the issue related to `gitdb error`.
So I would suggest that you pull the latest changes and then try it.

**Comment by steve7158** [comment]
@JesseBowling, @mzfr, @Harmon758 I think the version issue for gitdb is anylonger a problem should we close this issue?  :relaxed:

**Comment by JesseBowling** [comment]
Yep, master works for me!
