### ISSUE TITLE
Clone utf-8 url

### ISSUE THREAD

**Issue by afeena** [mushorg/snare#45]
When trying to clone page, which has url with utf-8 characters, this error occurs

```
http://mainnika.ru/%F0%9F%98%BC/
Traceback (most recent call last):
  File "/opt/snare/clone.py", line 167, in <module>
    main()
  File "/opt/snare/clone.py", line 163, in main
    loop.run_until_complete(cloner.run())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/opt/snare/clone.py", line 147, in run
    return (yield from self.get_body())
  File "/opt/snare/clone.py", line 113, in get_body
    if file_path and not os.path.exists(file_path):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-31: ordinal not in range(128)
```

**Comment by mzfr** [comment]
Hi @afeena , I tried to clone the same url with 
this [python3 clone.py --target  http://mainnika.ru/%F0%9F%98%BC/] command and there was no problem in cloning.
This [path:  /opt/snare/pages/mainnika.ru/😼 name:  😼] was the output

**Comment by afeena** [comment]
I guess it is because now we store paths as md5 hashes, and `os.path.exists(file_path)` no longer has problems with such a path

**Comment by mzfr** [comment]
ok, so since this problem does not exist anymore we can close the issue right ?

**Comment by afeena** [comment]
Yes, you are right :)
