### ISSUE TITLE
example.com Exceptions

### ISSUE THREAD

**Issue by tknecht** [mushorg/snare#47]
Installed everything as described.

```
root@docker:~/snare# sudo python3 snare.py --port 8080 --page-dir example.com

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

privileges dropped, running as "nobody:nogroup"
serving on ('0.0.0.0', 8080) with uuid f39fedba-6128-4958-ad4f-a702a0a574ea
you are running the latest version
Request path: /
Request path: /favicon.ico
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 220, in handle_request
    content_type = magic.from_file(path, mime=True)
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 131, in from_file
    return m.from_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 81, in from_file
    with open(filename):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/snare/pages/example.com/favicon.ico'
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:213> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 220, in handle_request
    content_type = magic.from_file(path, mime=True)
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 131, in from_file
    return m.from_file(filename)
  File "/usr/local/lib/python3.5/dist-packages/magic.py", line 81, in from_file
    with open(filename):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/snare/pages/example.com/favicon.ico'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 304, in start
    yield from self.handle_error(500, message, None, exc)
TypeError: 'NoneType' object is not iterable
Request path: /inform
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 171, in handle_request
    post_data = MultiDict(parse_qsl(post_data.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 9: invalid start byte
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:213> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 171, in handle_request
    post_data = MultiDict(parse_qsl(post_data.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 9: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 304, in start
    yield from self.handle_error(500, message, None, exc)
TypeError: 'NoneType' object is not iterable
Request path: /inform
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 171, in handle_request
    post_data = MultiDict(parse_qsl(post_data.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 9: invalid start byte
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:213> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 261, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 171, in handle_request
    post_data = MultiDict(parse_qsl(post_data.decode('utf-8')))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 9: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 304, in start
    yield from self.handle_error(500, message, None, exc)
TypeError: 'NoneType' object is not iterable
```

**Comment by afeena** [comment]
Is this exception occurs when you open the main page?

**Comment by tknecht** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/opt/snare/pages/example.com/favicon.ico' occurs when opening the main page.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 9: invalid start byte occurs frequently without opening the page or without any traffic on the page.

**Comment by afeena** [comment]
Thanks for the issue =) I've found the problem, this should help #48  
Please, if you try this, give me some feedback =)

**Comment by glaslos** [comment]
Change merged, please check if this fixed your issues.
