### ISSUE TITLE
Internal server error 500 

### ISSUE THREAD

**Issue by santiago92** [mushorg/snare#5]
when execute snare: 
Request path: /
Error handling request
```python
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 114, in handle_request
    if 'payload' in event_result['response']['message']['detection']:
KeyError: 'message'
Request path: /favicon.ico
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 114, in handle_request
    if 'payload' in event_result['response']['message']['detection']:
KeyError: 'message'
```

**Comment by glaslos** [comment]
Issue was in a failed deploy to the TANNER service https://github.com/mushorg/tanner/commit/932249c0b67ce7aeb3a4e7b9118ce428fdf303ef. As soon as I'm back home with access to the server I will upgrade the service.

**Comment by glaslos** [comment]
just deployed the fixed tanner service and tested the current snare version. All works fine. Thanks for reporting.
