### ISSUE TITLE
can't start snare.py

### ISSUE THREAD

**Issue by perl2php** [mushorg/snare#83]
hello
i'm really new to python
installed snare as described
system is ubuntu 16.04, python3 3.5.2
when trying to start:

ubuntu@test:~/snare$ sudo python3 snare.py --port 8080 --page-dir example.com
Traceback (most recent call last):
  File "snare.py", line 37, in <module>
    from aiohttp.web import StaticResource as StaticRoute
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/web.py", line 10, in <module>
    from . import (hdrs, web_exceptions, web_middlewares, web_reqrep, web_server,
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 17, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "snare.py", line 39, in <module>
    from aiohttp.web import StaticResource
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/web.py", line 10, in <module>
    from . import (hdrs, web_exceptions, web_middlewares, web_reqrep, web_server,
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 17, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'

what should i do?

**Comment by afeena** [comment]
Hi, please run 
```pip3 freeze``` 
and show the output

Seems like you have problems with yarl version 
https://github.com/aio-libs/aiohttp/issues/2662

**Comment by perl2php** [comment]
ubuntu@test:~$  pip3 freeze
aiohttp==1.3.5
async-timeout==2.0.0
beautifulsoup4==4.6.0
blinker==1.3
chardet==3.0.4
cloud-init==17.1
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
cssutils==1.0.2
gitdb2==2.0.3
GitPython==2.1.8
idna==2.6
Jinja2==2.8
jsonpatch==1.10
jsonpointer==1.9
language-selector==0.1
MarkupSafe==0.23
multidict==4.0.0
netifaces==0.10.6
oauthlib==1.0.3
prettytable==0.7.2
pyasn1==0.1.9
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyserial==3.0.1
python-apt==1.1.0b1
python-debian==0.1.27
python-magic==0.4.15
python-systemd==231
PyYAML==3.11
requests==2.9.1
six==1.10.0
smmap2==2.0.3
ssh-import-id==5.5
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
virtualenv==15.0.1
yarl==1.1.0

**Comment by afeena** [comment]
Yeah, you have yarl==1.1.0, try to install yarl==0.9.8 (I have this version and snare starts without any problem)

**Comment by afeena** [comment]
Yeah, you can make a pr :)

**Comment by afeena** [comment]
#85
