### ISSUE TITLE
504 Gateway Timeout The gateway server did not receive a timely response 

### ISSUE THREAD

**Issue by terakoh** [mushorg/snare#97]
Hi all, I received this error when I started snare. Previously, I don't recall having problem starting up snare and tanner on the same machine. This error seems to occur after I tried to configure tanner on another machine. Afterwhich, when I try to run tanner and snare on the same machine, I got this error also.

privileges dropped, running as "nobody:nogroup"
serving on ('127.0.0.1', 80) with uuid 5a525b99-2d9a-4bd3-9c8f-0570e4e31cc4
you are running the latest version
Request path: /
snare.py:273: RuntimeWarning: coroutine 'HttpRequestHandler.submit_data' was never awaited
  self.submit_data(data)
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:225> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "snare.py", line 123, in submit_data
    'http://{0}:8090/event'.format(self.run_args.tanner), data=json.dumps(data)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 582, in __await__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 220, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 614, in start
    message = yield from httpstream.read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/streams.py", line 625, in read
    result = yield from super().read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/streams.py", line 456, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 275, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 178, in handle_request
    event_result = await self.submit_data(data)
  File "snare.py", line 132, in submit_data
    raise e
  File "snare.py", line 130, in submit_data
    r.release()
  File "/usr/local/lib/python3.5/dist-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.5/dist-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 311, in start
    yield from self.handle_error(504, message)
TypeError: 'NoneType' object is not iterable
Request path: /favicon.ico
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/local/lib/python3.5/dist-packages/aiohttp/server.py:225> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "snare.py", line 123, in submit_data
    'http://{0}:8090/event'.format(self.run_args.tanner), data=json.dumps(data)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 582, in __await__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 220, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 614, in start
    message = yield from httpstream.read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/streams.py", line 625, in read
    result = yield from super().read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/streams.py", line 456, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 275, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 178, in handle_request
    event_result = await self.submit_data(data)
  File "snare.py", line 132, in submit_data
    raise e
  File "snare.py", line 130, in submit_data
    r.release()
  File "/usr/local/lib/python3.5/dist-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.5/dist-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 311, in start
    yield from self.handle_error(504, message)
TypeError: 'NoneType' object is not iterable

**Comment by terakoh** [comment]
I found the reason already.
It is due to my mongo database not started, so there is a timeout waiting for tanner to reply.
